# coding: utf-8

"""
    R1 Common definitions

    R1 Common definitions - O-RAN.WG2.R1AP_Common.yaml. © 2024, O-RAN ALLIANCE. All rights reserved. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI


app = FastAPI(
    title="R1 Common definitions",
    description="R1 Common definitions - O-RAN.WG2.R1AP_Common.yaml. © 2024, O-RAN ALLIANCE. All rights reserved. ",
    version="1.0.0",
)

