# coding: utf-8

"""
    Data registration service

    API for Data registration service. © 2024, O-RAN ALLIANCE. All rights reserved. 

    The version of the OpenAPI document: 2.0.0-alpha.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DataDeliveryMode(str, Enum):
    """
    This indicates whether the data instance is created in a one-time data delivery (data request) or continuously (data subscription)
    """

    """
    allowed enum values
    """
    ONE_TIME = 'ONE_TIME'
    CONTINUOUS = 'CONTINUOUS'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataDeliveryMode from a JSON string"""
        return cls(json.loads(json_str))


