# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ProblemDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, title: str=None, status: float=None, detail: str=None, instance: str=None):
        """ProblemDetails - a model defined in OpenAPI

        :param type: The type of this ProblemDetails.
        :param title: The title of this ProblemDetails.
        :param status: The status of this ProblemDetails.
        :param detail: The detail of this ProblemDetails.
        :param instance: The instance of this ProblemDetails.
        """
        self.openapi_types = {
            'type': str,
            'title': str,
            'status': float,
            'detail': str,
            'instance': str
        }

        self.attribute_map = {
            'type': 'type',
            'title': 'title',
            'status': 'status',
            'detail': 'detail',
            'instance': 'instance'
        }

        self._type = type
        self._title = title
        self._status = status
        self._detail = detail
        self._instance = instance

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ProblemDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ProblemDetails of this ProblemDetails.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this ProblemDetails.

        a URI reference according to IETF RFC 3986 that identifies the problem type

        :return: The type of this ProblemDetails.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ProblemDetails.

        a URI reference according to IETF RFC 3986 that identifies the problem type

        :param type: The type of this ProblemDetails.
        :type type: str
        """

        self._type = type

    @property
    def title(self):
        """Gets the title of this ProblemDetails.

        human-readable summary of the problem type

        :return: The title of this ProblemDetails.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ProblemDetails.

        human-readable summary of the problem type

        :param title: The title of this ProblemDetails.
        :type title: str
        """

        self._title = title

    @property
    def status(self):
        """Gets the status of this ProblemDetails.

        the HTTP status code

        :return: The status of this ProblemDetails.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ProblemDetails.

        the HTTP status code

        :param status: The status of this ProblemDetails.
        :type status: float
        """

        self._status = status

    @property
    def detail(self):
        """Gets the detail of this ProblemDetails.

        human-readable explanation 

        :return: The detail of this ProblemDetails.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this ProblemDetails.

        human-readable explanation 

        :param detail: The detail of this ProblemDetails.
        :type detail: str
        """

        self._detail = detail

    @property
    def instance(self):
        """Gets the instance of this ProblemDetails.

        URI reference that identifies the specific occurrence of the problem

        :return: The instance of this ProblemDetails.
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this ProblemDetails.

        URI reference that identifies the specific occurrence of the problem

        :param instance: The instance of this ProblemDetails.
        :type instance: str
        """

        self._instance = instance
