from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DataDeliveryMode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ONE_TIME = 'ONE_TIME'
    CONTINUOUS = 'CONTINUOUS'
    def __init__(self):  # noqa: E501
        """DataDeliveryMode - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DataDeliveryMode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataDeliveryMode of this DataDeliveryMode.  # noqa: E501
        :rtype: DataDeliveryMode
        """
        return util.deserialize_model(dikt, cls)
