from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.schema_types import SchemaTypes
from openapi_server import util

from openapi_server.models.schema_types import SchemaTypes  # noqa: E501

class DeliverySchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, delivery_schema_id=None, _schema=None):  # noqa: E501
        """DeliverySchema - a model defined in OpenAPI

        :param type: The type of this DeliverySchema.  # noqa: E501
        :type type: SchemaTypes
        :param delivery_schema_id: The delivery_schema_id of this DeliverySchema.  # noqa: E501
        :type delivery_schema_id: str
        :param _schema: The _schema of this DeliverySchema.  # noqa: E501
        :type _schema: str
        """
        self.openapi_types = {
            'type': SchemaTypes,
            'delivery_schema_id': str,
            '_schema': str
        }

        self.attribute_map = {
            'type': 'type',
            'delivery_schema_id': 'deliverySchemaId',
            '_schema': 'schema'
        }

        self._type = type
        self._delivery_schema_id = delivery_schema_id
        self.__schema = _schema

    @classmethod
    def from_dict(cls, dikt) -> 'DeliverySchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeliverySchema of this DeliverySchema.  # noqa: E501
        :rtype: DeliverySchema
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> SchemaTypes:
        """Gets the type of this DeliverySchema.


        :return: The type of this DeliverySchema.
        :rtype: SchemaTypes
        """
        return self._type

    @type.setter
    def type(self, type: SchemaTypes):
        """Sets the type of this DeliverySchema.


        :param type: The type of this DeliverySchema.
        :type type: SchemaTypes
        """

        self._type = type

    @property
    def delivery_schema_id(self) -> str:
        """Gets the delivery_schema_id of this DeliverySchema.

        A Data Producer may support one or more delivery schemas and for each supported schema type a delivery schema identifier is assigned. A Data Consumer uses this attribute while creating a data job and request to deliver the data using specific schema type which is identified by this attribute.  # noqa: E501

        :return: The delivery_schema_id of this DeliverySchema.
        :rtype: str
        """
        return self._delivery_schema_id

    @delivery_schema_id.setter
    def delivery_schema_id(self, delivery_schema_id: str):
        """Sets the delivery_schema_id of this DeliverySchema.

        A Data Producer may support one or more delivery schemas and for each supported schema type a delivery schema identifier is assigned. A Data Consumer uses this attribute while creating a data job and request to deliver the data using specific schema type which is identified by this attribute.  # noqa: E501

        :param delivery_schema_id: The delivery_schema_id of this DeliverySchema.
        :type delivery_schema_id: str
        """

        self._delivery_schema_id = delivery_schema_id

    @property
    def _schema(self) -> str:
        """Gets the _schema of this DeliverySchema.

        The schema serialized to string. If this attribute is not present, the schema is assumed to be known from the DME type definition that is referenced by dmeTypeId  # noqa: E501

        :return: The _schema of this DeliverySchema.
        :rtype: str
        """
        return self.__schema

    @_schema.setter
    def _schema(self, _schema: str):
        """Sets the _schema of this DeliverySchema.

        The schema serialized to string. If this attribute is not present, the schema is assumed to be known from the DME type definition that is referenced by dmeTypeId  # noqa: E501

        :param _schema: The _schema of this DeliverySchema.
        :type _schema: str
        """

        self.__schema = _schema
