# coding: utf-8

# flake8: noqa
"""
    R1 Common definitions

    R1 Common definitions - O-RAN.WG2.R1AP_Common.yaml. © 2024, O-RAN ALLIANCE. All rights reserved. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.problem_details import ProblemDetails
