openapi: 3.0.3
info:
  description: |
    R1 Common definitions - O-RAN.WG2.R1AP_Common.yaml.
    © 2024, O-RAN ALLIANCE.
    All rights reserved.
  title: R1 Common definitions
  version: 1.0.0
externalDocs:
  description: O-RAN.WG2.R1AP-v06.00
  url: https://www.o-ran.org/specifications
servers:
- url: /
paths: {}
components:
  responses:
    "400":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Bad Request
    "401":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unauthorized
    "403":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Forbidden
    "404":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Found
    "405":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Method Not Allowed
    "406":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Acceptable
    "409":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Conflict
    "411":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Length Required
    "413":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Payload Too Large
    "414":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: URI Too Large
    "415":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unsupported Media Type
    "429":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Too Many Requests
    "500":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Internal Server Error
    "502":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Bad Gateway
    "503":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Service Unavailable
  schemas:
    Uri:
      description: "A string formatted according to IETF RFC 3986 [8]."
      type: string
    ProblemDetails:
      description: A problem detail to carry details in an HTTP response according
        to RFC 7807
      properties:
        type:
          description: a URI reference according to IETF RFC 3986 that identifies
            the problem type
          type: string
        title:
          description: human-readable summary of the problem type
          type: string
        status:
          description: the HTTP status code
          type: number
        detail:
          description: 'human-readable explanation '
          type: string
        instance:
          description: URI reference that identifies the specific occurrence of the
            problem
          type: string
      type: object
